### ISSUE TITLE
Discord Cringe

### ISSUE THREAD

**Issue by AsgerJon** [Wynncraft-Distant-Horizons-Data/lods-v1#10]
So because the discord server requires you to find a secret in the FAQ or something, I will just post my question here.

If a mod such as chunky or fabric pregen were to pregenerate chunks right after world creation in a single-player world, would those chunks thus pregenerated be rendered by Distant Horizons, or must the chunks have been traversed by a player? I ask because members of the chunky discord believe this to be the case. 

Things like the secret code to be allowed to ask questions in the discord is unacceptable.

**Comment by AsgerJon** [comment]
-

**Comment by coolGi2007** [comment]
You should probably make an issue on DH's main git location, rather than a repo dedicated to storing data for a certain server\
https://gitlab.com/jeseibel/distant-horizons

(or you could read through the faq and ask on the server)

**Comment by obj-obj** [comment]
> If a mod such as chunky or fabric pregen were to pregenerate chunks right after world creation in a single-player world, would those chunks thus pregenerated be rendered by Distant Horizons, or must the chunks have been traversed by a player? I ask because members of the chunky discord believe this to be the case.

On a single-player world I'm pretty sure pregenerated chunks do show up, and distant horizons also has its own pregenerator built-in
